# =========================================================
#             DESTINY TOWERS 26.3 / 26.2
# =========================================================

locale: es
enable_on_start: true

# Configuración del Sistema de Auto-Inicio
autostart:
  enabled: true
  count: 4          # Cantidad mínima de jugadores requeridos para iniciar
  countdown: 10     # Segundos de cuenta regresiva

# Modalidad de Selección de Equipos (STANDARD, LEADER_VOTING, AUCTION_DRAFT)
selection_mode: STANDARD

# Configuración de Votación de Líder
voting:
  round_seconds: 20       # Duración en segundos de cada ronda de votación

# Configuración de Subasta (Auction Draft)
auction:
  initial_credits: 100    # Créditos iniciales para cada capitán
  turn_seconds: 15        # Segundos por turno para pujar por cada jugador

# Tiempo de Anuncio / Lectura de Reglas de Modo
modes:
  explanation_seconds: 60 # Segundos de espera para que los jugadores lean las reglas

# Cuenta atrás previa al inicio de partida tras selección/subasta
match:
  duration: 1200          # Duración en segundos (20 minutos)
  maxpoints: 10           # Puntos necesarios para ganar
  weather: CLEAR          # Clima fijo durante la partida
  time: 6000              # Hora fija del mundo (mediodía)
  prestart_countdown: 10  # Segundos de conteo antes de soltar a los jugadores
# Configuración de Regeneración Automática del Mapa sin Reinicio
rollback:
  auto_restore_on_end: true
  clean_entities: true

# Control de Eventos de Caos Dinámicos
events:
  enabled: true

# Control de la Tienda Táctica del Faro
beacon_shop:
  enabled: true

# Integración de Chat de Voz (Simple Voice Chat API)
voicechat:
  enabled: true
  isolated: true

# Puntos de Mapa
map:
  lobby:
    world: the-towers
    x: 0.5
    y: 200.0
    z: 1000.0
    yaw: 0.0
    pitch: 0.0

# Equipos
teams:
  Red:
    color: RED
    spawn:
      world: the-towers
      x: 84.5
      y: 192.0
      z: 1152.5
      yaw: 0.0
      pitch: 0.0
    cage:
      world: the-towers
      x: 84.5
      y: 200.0
      z: 1152.5
      yaw: 0.0
      pitch: 0.0
  Blue:
    color: BLUE
    spawn:
      world: the-towers
      x: -83.5
      y: 192.0
      z: 1152.5
      yaw: 0.0
      pitch: 0.0
    cage:
      world: the-towers
      x: -83.5
      y: 200.0
      z: 1152.5
      yaw: 0.0
      pitch: 0.0

# Generadores de Recursos (Configurables mediante /ttr set <tipo>)
spawns:
  iron: []
  coal: []
  emerald: []
  xp: []
