name: DestinyTowers
version: 1.0.0
main: me.PauMAVA.TTR.TTRCore
api-version: '26.2'
softdepend: [voicechat]
authors: [PauMAVA, StartCes, Ripkyng1, ElGlower]
description: Destiny Towers para Paper 26.3 / 26.2 con regeneracion atomica de mapa, Tiny Font, panel GUI y modo pantalla (Book Screen)

commands:
  destinytowers:
    description: Comando principal de Destiny Towers
    aliases: [dt, ttr, thetowers, towers, destiny]
  dt:
    description: Comando abreviado de Destiny Towers
    aliases: [destinytowers]
  ttr:
    description: Comando heredado de The Towers
    aliases: [destinytowers]
  bid:
    description: Pujar en la subasta activa
    aliases: [dtbid, puja]
  stats:
    description: Ver estadísticas del jugador
    aliases: [estadisticas, dtstats]
  setlobby:
    description: Establece el punto de aparición del Lobby
    permission: destinytowers.admin
  ttrstart:
    description: Inicia la partida
    permission: destinytowers.admin
    aliases: [dtstart]
  ttrstop:
    description: Detiene la partida
    permission: destinytowers.admin
    aliases: [dtstop]
  ttrset:
    description: Configura el mapa, spawns y jaulas
    permission: destinytowers.admin
    aliases: [dtset]
  ttrenable:
    description: Activa el plugin
    permission: destinytowers.admin
    aliases: [dtenable]
  ttrdisable:
    description: Desactiva el plugin
    permission: destinytowers.admin
    aliases: [dtdisable]
  ttrrevive:
    description: Revive a un jugador en su base
    permission: destinytowers.admin
    aliases: [dtrevive]
  ttrforcejoin:
    description: Fuerza la entrada de un jugador a un equipo
    permission: destinytowers.admin
    aliases: [dtforcejoin]
  ttrconfig:
    description: Configura opciones en vivo (tiempo, puntos)
    permission: destinytowers.admin
    aliases: [dtconfig]
  ttrevent:
    description: Controla y lanza eventos de caos
    permission: destinytowers.admin
    aliases: [dtevent]
  ttrspectate:
    description: Poner a un jugador en modo espectador
    permission: destinytowers.admin
    aliases: [dtspectate]
  ttrplay:
    description: Salir del modo espectador y entrar a la partida
    permission: destinytowers.admin
    aliases: [dtplay]
  ttrresetmap:
    description: Fuerza la regeneración del mapa a su estado original
    permission: destinytowers.admin
    aliases: [dtresetmap]

permissions:
  destinytowers.admin:
    description: Permiso de administración total de Destiny Towers
    default: op
  destinytowers.player:
    description: Permiso para jugadores de Destiny Towers
    default: true
  ttr.admin:
    description: Permiso de administración heredado
    default: op
  ttr.player:
    description: Permiso para jugadores heredado
    default: true