name: TheTowersRemastered
version: 1.4-1.21
main: me.PauMAVA.TTR.TTRCore
api-version: 1.21
authors: [PauMAVA, ElGlower]
description: The Towers Remastered para la 1.21

commands:
  ttrstart:
    description: Inicia la partida
    permission: ttr.admin
  ttrstop:
    description: Detiene la partida
    permission: ttr.admin
  ttrset:
    description: Configura el mapa y spawns
    permission: ttr.admin
  ttrenable:
    description: Activa el plugin
    permission: ttr.admin
  ttrdisable:
    description: Desactiva el plugin
    permission: ttr.admin
  ttrrevive:
    description: Revive a un jugador
    permission: ttr.admin
  ttrforcejoin:
    description: Fuerza entrada a equipo
    permission: ttr.admin
  ttrconfig:
    description: Configura opciones
    permission: ttr.admin
  ttrevent:
    description: Controla los eventos
    permission: ttr.admin
  ttrspectate:
    description: Poner en espectador a alguien
    permission: ttr.admin
  ttrplay:
    description: Salir del modo espectador