name: TheTowersRemastered
version: 1.4-1.21
main: me.PauMAVA.TTR.TTRCore
api-version: 1.21
commands:
  ttrenable:
    description: Habilita el juego
    permission: ttr.admin
  ttrdisable:
    description: Deshabilita el juego
    permission: ttr.admin
  ttrstart:
    description: Inicia partida manualmente
    permission: ttr.admin
  ttrset:
    description: Configurar mapa y spawns
    permission: ttr.admin
  ttrstop:
    description: Detener partida forzosamente
    permission: ttr.admin
  ttrrevive:
    description: Revivir jugador
    permission: ttr.admin
  ttrforcejoin:
    description: Meter jugador a un equipo y equiparlo
    permission: ttr.admin
  ttrconfig:
    description: Configurar tiempo y puntos en vivo
    permission: ttr.admin
  ttrevent:
    description: Controlar eventos aleatorios
    permission: ttr.admin
permissions:
  ttr.admin:
    description: Permiso administrativo total
    default: op